seed: 0

train:
  num_epochs: 1
  minibatch_size: 4096
  lr: 1e-5
  max_grad_norm: 40.0
  device: ???

env:
  max_steps: 100
  scenario_name: "balance"
  scenario:
    n_agents: 3
  device: ???
  num_envs: ??

model:
  shared_params: True
  centralised_critic: True

collector:
  frames_per_batch: 60_000
  n_iters: 500
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.9
  lmbda: 0.9
  entropy_eps: 0.01

eval: 
  frequency: 10

logger:
  
